# Practice 4: Modules and files

## Part 1: Commonly used modules

### Exercise 1

Generate the numpy matrix in the fastest way possible, using np.arange(). Note: do not manually write down each element, and the solution should not exceed two lines

[[ 1  6 11 16  2] <br/>
 [ 7 12 17  3  8] <br/>
 [13 18  4  9 14] <br/>
 [19  5 10 15 20]]

In [ ]:
import numpy as np
print(np.arange(1,21))
print(np.arange(1,21).reshape(5,4,order = 'f'))
print(np.arange(1,21).reshape(5,4,order = 'f').reshape(4,5))

## Exercise 2

Write a function to convert the numpy matrix into percentage matrix: each element in a line is converted into its percentage of the sum of elements in that line (no need for rounding)

In [ ]:
import numpy as np
def convert(a):
    return a/np.sum(a, axis = 1, keepdims = True)
x = np.array([[1,2,4],[3,1,4],[1,5,6]])
convert(x)

### Exercise 3

Solve the system of linear equation Ax = b, knowing the augmented matrix [A|b]. It is guarantee that the system of linear equation has n equations, n variables and a single solution

In [ ]:
import numpy as np
def system_solver(a):
    X = a[:,:len(a[0])-1]
    y = a[:,-1]
    return np.linalg.solve(X,y).reshape(len(a),1)     
def system_solver1(a):
    slt = [0 for i in range (len(a))]
    for i in range (len(a)):
        a[i].append(b[i])
    for i in range (len(a)):
        for j in range(i+1,len(a)):
            for k in range(len(a[0])):
                a[j][k] = a[j][i]*a[i][k]-a[i][i]*a[j][k]
    for i in range (len(a)):
        slt[i] = a[-i-1][-1]
        for j in range (i):
            slt[i] -= slt[j]*a[-i-1][-i-1]
        slt[i] /= a[-1-i][-i-2]
    return slt.reverse()

### Exercise 4

Plot the function y = sin(2x) and y = cos(2x) in the range [-4, 4] on the same plot as below using matplotlib



In [ ]:
import matplotlib.pyplot as plt
import numpy as np
x = np.arange(-4,4,0.01)
y = np.sin(2*x)
z = np.cos(2*x)
plt.plot(x,y,color = 'blue')
plt.plot(x,z,color = 'red')
plt.show()

## Part 2: Modularize a Python program

### Exercise 5

Write a module that contains the constant pi and implementations of these mathematics function: exp, sin, cos using Maclaurin series. The result should be computed with 9 exact decimal places and rounded to 6 digits after the comma. Note: you should implement your own function, and do not use function from other libraries

The module will be used for testing later

Module name: trig.py

### Exercise 6

In [15]:
import trig
import math
n = float(input())
a = 0
b = 0
for i in range (1,21):
    if i % 2 == 0:
        a += trig.cosine(n+i)
        b += round(math.cos(n+i),6)
    else:
        a += trig.sine(n+i)
        b += round(math.sin(n+i),6)
print('Your own implementation:     %f' % round(a,6))
print('Math module implementation:  %f' % round(b,6))


24
Your own implementation:     0.242187
Math module implementation:  0.242190


## Part 3: Files

### Exercise 7

In [11]:
with open('test.inp') as f:
    d = {}
    for line in f:
        lst = line.split(' ')
        for i in lst:
            if i not in d:
                d[i] = 1
            else:
                d[i] += 1
with open('test.out','w') as f:
    f.write(str(d))
with open('test.out', 'r') as f:
    all = f.read()
    print(all)

{'This': 3, 'is': 3, 'a': 1, 'sentence\n': 3, 'the': 2, 'second': 1, 'last': 1}


### Exercise 8

In [14]:
import pickle
a = [int(i) for i in input().split()]
b = [int(i) for i in input().split()]
f = open('list.pkl','wb')
pickle.dump((a,b),f)
f.close()
with open('list.pkl', 'rb') as f:
    c, d = pickle.load(f)
    result = [i + j for i, j in zip(c, d)]
    print(result)

1 2 3
4 5 6
[5, 7, 9]


### Exercise 9

In [20]:
def add_student_info(new):
    if 'id' not in new:
        return None
    with open('student_info.pkl', 'rb') as f:
        x = pickle.load(f)
    f.close()
    duplicate = False
    for i in x:
        if i['id'] == new['id']:
            x[x.index(i)] = new
            break
    else:
        x.append(new)
    with open('updated_info.pkl', 'wb') as f:
        pickle.dump(x, f)
    f.close()